### ISSUE TITLE
not working in Wine

### ISSUE THREAD

**Issue by arduinka55055** [Macsimka/MopLauncher#2]
i tried to execute launcher with Wine, but i got error(file attached)
[crashlog.txt](https://github.com/Macsimka/MopLauncher/files/5040227/crashlog.txt)

error is not complicated, i think. Its just unhandled exception in some xaml parser(i am not expert in C#)
i hope your team will fix it, because launcher will be necessary soon for battlegrounds.(or i just did some wrong way, but all important libraries was installed here https://forum.pandawow.ru/showthread.php?t=12)

P.S. game works fine and smoothly without bugs, problem is in launcher (or my crabby hands)

**Comment by arduinka55055** [comment]
wine-mono and winetricks also installed

**Comment by Macsimka** [comment]
Only windows support now,

**Comment by arduinka55055** [comment]
i wanted to help, give you some dumps under wine if you need.
Tnanks!
